services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092" 
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped

  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: "kafka:9092" 
    restart: unless-stopped

  frontend:
    build: ./nextjs-frontend  
    container_name: nextjs_frontend
    ports:
      - "3000:3000" 
    restart: always

  apigateway:
    image: ddrmin/api-gateway:latest
    container_name: apigateway
    restart: always
    ports:
      - "5000:5000" 
    volumes:
      # This maps your local Firebase key to a path inside the container 
      - ./firebase-service-account.json:/app/firebase-service-account.json
    environment:
      # Server Configuration
      - PORT=${APIGATEWAY_PORT}
      - NODE_ENV=${NODE_ENV}

      # Firebase Configuration (path is now inside the container)
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}

      # Backend Services URLs (using Docker service names) 
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - EVENT_SERVICE_URL=${EVENT_SERVICE_URL}
      - TICKET_SERVICE_URL=${TICKET_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - PUBLIC_SERVICE_URL=${PUBLIC_SERVICE_URL}

      # Security Configuration
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

      # Rate Limiting
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}

      # Proxy Configuration
      - PROXY_TIMEOUT=${PROXY_TIMEOUT}

      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL}

  
  notifi:
    image: your-dockerhub-username/notification-service:latest
    container_name: notification_service
    # No 'ports' needed unless you want to access it directly from the host
    # The API gateway can reach it using its service name and internal port (e.g., 5000)

  event:
    image: your-dockerhub-username/event-service:latest
    container_name: event_service

  ticket:
    image: ddrmin/ticket-and-order-service:latest
    container_name: ticket_service
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json
    environment:
      - DATABASE_URL=${TICKET_SERVICE_DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}
      - REDIS_URL=${REDIS_URL}
      - APIGATEWAY_DOCKER_URL=${APIGATEWAY_URL}

  redis:
    image: "redis:alpine"
    container_name: redisDB
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - "${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro"
    ports:
      - "9999:8080"

volumes:
  redis-data:
  kafka_data:
    driver: local
