services:
  frontend:
    build: ./nextjs-frontend  # Tells Docker to build the image from this folder
    container_name: nextjs_frontend
    ports:
      - "3000:3000" 
    restart: always

  apigateway:
    image: ddrmin/api-gateway:latest
    container_name: apigateway
    restart: always
    ports:
      - "5000:5000" 
    volumes:
      # This maps your local Firebase key to a path inside the container 
      - ./firebase-service-account.json:/app/firebase-service-account.json
    environment:
      # Server Configuration
      - PORT=${APIGATEWAY_PORT}
      - NODE_ENV=${NODE_ENV}

      # Firebase Configuration (path is now inside the container)
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}

      # Backend Services URLs (using Docker service names) 
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - EVENT_SERVICE_URL=${EVENT_SERVICE_URL}
      - TICKET_SERVICE_URL=${TICKET_SERVICE_URL}
      - PUBLIC_SERVICE_URL=${PUBLIC_SERVICE_URL}

      # Security Configuration
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

      # Rate Limiting
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}

      # Proxy Configuration
      - PROXY_TIMEOUT=${PROXY_TIMEOUT}

      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL}

  
  notifi:
    image: your-dockerhub-username/notification-service:latest
    container_name: notification_service
    # No 'ports' needed unless you want to access it directly from the host
    # The API gateway can reach it using its service name and internal port (e.g., 5000)

  event:
    image: your-dockerhub-username/event-service:latest
    container_name: event_service

  ticket:
    image: ddrmin/ticket-and-order-service:latest
    container_name: ticket_service
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json
    environment:
      - DATABASE_URL=${TICKET_SERVICE_DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}
      - REDIS_URL=${REDIS_URL}
      - APIGATEWAY_DOCKER_URL=${APIGATEWAY_URL}

  redis:
    image: "redis:alpine"
    container_name: redisDB
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
